project: 
  type: website


format: html
website:
  title: "Josh Medrano, Ph.D."
  google-analytics: "G-WY0TP47DPN"
  navbar:
    title: Josh Medrano, Ph.D.
    search: false
    background: info
    right:
    - href: index.qmd
      text: Home
    - href: cv.qmd
    - href: publications.qmd
    - href: research.qmd
    
theme:
  - journal
  - custom.scss
  
output: html