project: 
  type: website
  output-dir: docs

format: 
  html:
    fig-format: svg
    
website:
  title: "Josh Medrano, Ph.D."
  google-analytics: "G-WY0TP47DPN"
  page-navigation: true
  navbar:
    title: Josh Medrano, Ph.D.
    search: false
    pinned: true
    collapse: false
    right:
    - text: About
      href: index.qmd
    - text: CV
      href: about.qmd
    - text: Research
      href: research.qmd
    # - text: Science Communication
    #   menu:
    #     - href: publications.qmd
    #     - href: presentations.qmd
    - href: thoughts.qmd
      text: Thoughts

title-block-banner: false
title-block-banner-color: black

theme:
  - simplex
  - custom.scss

