project: 
  type: website
  output-dir: docs

format: html
website:
  title: "Josh Medrano, Ph.D."
  google-analytics: "G-WY0TP47DPN"
  page-navigation: true
  navbar:
    title: Josh Medrano, Ph.D.
    search: false
    background: info
    pinned: true
    right:
    - text: Home
      href: index.qmd
    - text: About Me
      href: about.qmd
    - text: Research
      href: research.qmd
    - text: Science Communication
      menu:
        - href: publications.qmd
        - href: presentations.qmd
    - href: thoughts/index.qmd
      text: Thoughts

title-block-banner: true
title-block-banner-color: white

theme:
  - journal
  - custom.scss

