project: 
  type: website
  output-dir: docs

format: html
website:
  title: "Josh Medrano, Ph.D."
  google-analytics: "G-WY0TP47DPN"
  page-navigation: true
  navbar:
    title: Josh Medrano, Ph.D.
    search: false
    background: info
    pinned: true
    right:
    - href: index.qmd
      text: Home
    - href: about.qmd
    - href: research.qmd
    - href: publications.qmd
    - href: thoughts/index.qmd
      text: Thoughts

title-block-banner: true

theme:
  - journal
  - custom.scss
  
